In [14]:
# CONCEPTS: tensor 
#           storage 
#           strides 
#           layout 
#           device 
#           dytype  

In [1]:
import torch

# Create a 2D tensor (3x4)
t = torch.tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

# Check the strides
print(t.stride())  # Output will be (4, 1) for a 3x4 tensor in row-major order


(4, 1)


In [12]:
t.size(), t.stride(), t.dtype, t.device, t.layout, t.is_contiguous()

(torch.Size([3, 4]),
 (4, 1),
 torch.int64,
 device(type='cpu'),
 torch.strided,
 True)

In [20]:
t_transposed = t.t()

In [22]:
t_transposed.size(),t_transposed.stride(), t_transposed.dtype, t_transposed.layout, t_transposed.is_contiguous()

(torch.Size([4, 3]), (1, 4), torch.int64, torch.strided, False)

In [23]:
t_transposed

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])

In [18]:
t.storage()

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 12]

In [26]:
# Transposing a tensor doesn't change how the data is stored in the memory. 
# PyTorch uses stride to represent the tensor as newly transformed form here.

In [27]:
# Strides are also the fundamental basis of how views work in PyTorch users

In [31]:
t[0,1]    # stride is (4,1), so 4*0 + 1*1 = 1; at index 1, the element is 2

tensor(2)

In [32]:
t[1]     # 1*4 + 0*1 = 4, and then use t.size to slice upto to next 4 elements

tensor([5, 6, 7, 8])

In [33]:
# metadatas play quite an important role in all kinds of operations we do with tensors

In [36]:
t[:,2]   # 0*4 + 1*2 = 2, then use t.size() to 

tensor([ 3,  7, 11])

In [37]:
# -------------- TENSOR WRAPPER --------------

In [38]:
# Implement a tensor wrapper when:
# 1. you want to add additional methods or properties to a tensor
# 2. you don't need to modify the  underlying tensor data or how it participates in gradient calculations
# 3. you additional functionality doesn't need to be preserved through the backward pass

In [41]:
# Implementing a Tensor Wrapper 
import torch

class MyTensorWrapper:
    def __init__(self, tensor):
        self.tensor = tensor

    def __repr__(self):
        return f"MyTensorWrapper of shape {self.tensor.shape}"

    # add custom methods here:
    def sum(self):
        return self.tensor.sum()


# now let's use our wrapper
tensor = torch.randn(3,4)
wrapped_t = MyTensorWrapper(tensor)

print(wrapped_t)
print(wrapped_t.sum())

MyTensorWrapper of shape torch.Size([3, 4])
tensor(0.9404)


In [43]:
tensor

tensor([[ 1.0104,  1.7513,  1.3724,  0.3835],
        [ 0.4214, -0.8968, -0.6653,  0.7394],
        [-0.0072, -2.2337,  1.0739, -2.0089]])

In [44]:
tensor.sum()

tensor(0.9404)

In [45]:
# If you want the tensor to behave differently during gradient calculation 
# in the backward pass, you need to use tensor extensions.
# otherwise, a wrapper class is simpler